
SRCS = \
bounds.c boundsint.c coord.c diag.c dudp_calc_3vel.c dudp_calc.c dump.c dump_ener.c fixup.c gaussj.c \
image.c initbase.c init.c interp.c lubksb.c ludcmp.c main.c metric.c \
mnewt.c nrutil.c phys.c ranc.c restart.c set_arrays.c set_grid.c \
step_ch.c tensor.c utoprim.c utoprim_2d.c utoprim_1d.c utoprim_1d_opt.c vchar.c transforms.c fail.c utoprim_ldz.c \
init_mpi.c boundmpi.c boundmpiint.c sources.c utoprim_1d_final.c \
utoprim_2d_final.c utoprim_5d2_final.c phys.ffde.c \
advance.c reconstructeno.c
 
OBJS = \
bounds.o boundsint.o coord.o diag.o dudp_calc_3vel.o dudp_calc.o dump.o dump_ener.o fixup.o gaussj.o \
image.o initbase.o init.o interp.o lubksb.o ludcmp.o main.o metric.o \
mnewt.o nrutil.o phys.o ranc.o restart.o set_arrays.o set_grid.o \
step_ch.o tensor.o utoprim.o utoprim_2d.o utoprim_1d.o utoprim_1d_opt.o vchar.o transforms.o fail.o utoprim_ldz.o \
init_mpi.o boundmpi.o boundmpiint.o sources.o utoprim_1d_final.o \
utoprim_2d_final.o  utoprim_5d2_final.o phys.ffde.o \
advance.o reconstructeno.o


